version: '3'
services:
  mongo:
    image: mongo:4.1.13-bionic
  bot:
    image: alexeigontarcyber/cyber_bot:0.9.0
    ports:
      - '4567:4567'
    volumes:
      - './config.prod.json:/usr/app/cyber_bot/config.json:ro'
