version: '3'
services:
  db:
    image: mongo:4.1.13-bionic
    ports:
      - '27017:27017'

  cache:
    image: redis:5.0.5-alpine
    ports:
      - '6379:6379'
  mqtt:
    image: eclipse-mosquitto:1.6.3
    ports:
      - '1883:1883'
